CC = $(ARCH)gcc
CXX = $(ARCH)g++
AS = $(ARCH)as
LD = $(ARCH)ld
AR = $(ARCH)ar

TARGET = tree list

CFLAGS = -O2 $(INCLUDES) -I../include
LDLIBS = -lm

all : $(TARGET)

clean :
	$(RM) *.o $(TARGET)

